services:
  nginx:
    ports:
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    restart: always

  web:
    build:
      target: production
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: always

  supabase-db:
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  rest:
    environment:
      - PGRST_DB_URI=postgres://${DB_USER}:${DB_PASSWORD}@supabase-db:5432/postgres
      - PGRST_JWT_SECRET=${JWT_SECRET}
    restart: always

volumes:
  postgres_data: